@echo off
title EWT
@emmcdl\emmcdl.exe -p com%1 -f %2 -d aboot -o %3aboot.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d abootbak -o %3abootbak.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d apdp -o %3apdp.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d batweak -o %3batweak.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d boot -o %3boot.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d cache -o %3cache.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d cmnlib -o %3cmnlib.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d cmnlib64 -o %3cmnlib64.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d cmnlib64bak -o %3cmnlib64bak.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d cmnlibbak -o %3cmnlibbak.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d config -o %3config.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d DDR -o %3DDR.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d devcfg -o %3devcfg.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d devcfgbak -o %3devcfgbak.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d devinfo -o %3devinfo.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d dip -o %3dip.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d dpo -o %3dpo.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d dsp -o %3dsp.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d factory -o %3factory.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d fingerid -o %3fingerid.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d fsc -o %3fsc.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d fsg -o %3fsg.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d keymaster -o %3keymaster.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d keymasterbak -o %3keymasterbak.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d keystore -o %3keystore.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d limits -o %3limits.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d logdump -o %3logdump.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d mcfg -o %3mcfg.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d mdtp -o %3mdtp.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d misc -o %3misc.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d modem -o %3modem.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d modemst1 -o %3modemst1.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d modemst2 -o %3modemst2.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d mota -o %3mota.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d msadp -o %3msadp.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d oem -o %3oem.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d persist -o %3persist.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d recovery -o %3recovery.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d rpm -o %3rpm.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d rpmbak -o %3rpmbak.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d sbl1 -o %3sbl1.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d sbl1bak -o %3sbl1bak.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d sec -o %3sec.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d splash -o %3splash.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d ssd -o %3ssd.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d syscfg -o %3syscfg.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d tz -o %3tz.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d tzbak -o %3tzbak.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d vendor -o %3vendor.%4
@emmcdl\emmcdl.exe -p com%1 -f %2 -d ztecfg -o %3ztecfg.%4
pause